# Configuration File for Travis-CI
sudo: false
addons:
 apt:
  packages:
   - liblapack-dev
   - gfortran
language: python
python:
  - "3.7"
install: travis_wait pip install -r vizitka/travis_requirements.txt
script:  coverage run run_tests.py
after_success: coveralls
